apiVersion: apps/v1
kind: Deployment
metadata:
  name: php-fastapi
spec:
  replicas: 3
  selector:
    matchLabels:
      role: php-fastapi
  template:
    metadata:
      labels:
        role: php-fastapi
    spec:
      containers:
      - name: php-fastapi
        image: damiangn/imagen_kevin:latest
        imagePullPolicy: IfNotPresent        
        ports:
        - containerPort: 8000
        command: ["/bin/sh", "-c", "uvicorn servidor:app --host 0.0.0.0 --port 8000"]
        env:
        - name: MYSQL_ROOT_PASSWORD
          value: "password"
        resources:
          requests:
            memory: "64Mi"
            cpu: "200m"
          limits:
            memory: "128Mi"
            cpu: "500m"
