apiVersion: v1
kind: Service
metadata:
  name: apacheser #nombre del servicio
spec:
  selector:
    app: apache #nombre de la aplicacion
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30000 #puerto externo
  type: NodePort #tipo de servicio
 
