apiVersion: v1
kind: Service
metadata:
  name: nginxser #nombre del servicio
spec:
  selector:
    app: nginx #nombre de la app a la que me vinculo 
  ports:
    - port: 80
      targetPort: 80
      nodePort: 30001 #puerto externo
  type: NodePort #tipo de servicio
 
